name: 'Test Report'
on:
  workflow_run:
    workflows: ['configCheck']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: config-results            # artifact name
          name: config Tests                  # Name of the check run which will be created
          path: '*.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx              # Format of test results